/* =====================================================
 * tarot-data.js · 78 张韦特塔罗牌
 * 牌面图片来自开源塔罗牌图集（Rider-Waite，公版），
 * 通过 jsDelivr CDN 引用，无需随站点打包。
 *   major/0m.jpg ~ major/21m.jpg
 *   cups|pentacles|swords|wands / {1-10,k,n,p,q}{c|p|s|w}.jpg
 * 释义为通用牌意整理，供抽牌后参考。
 * ===================================================== */
window.TAROT_DECK = [
  /* ---------- 大阿卡纳 22 张 ---------- */
  { id: 'm0', cn: '愚者', en: 'The Fool', img: 'major/0m.jpg',
    up: '全新的开始，自由、天真与无畏，勇敢迈出第一步。', rev: '鲁莽冲动、计划不周，或是对未知过度恐惧。' },
  { id: 'm1', cn: '魔术师', en: 'The Magician', img: 'major/1m.jpg',
    up: '创造力与行动力俱佳，资源都在你手上，心想事成。', rev: '空有想法却不行动，或被花言巧语蒙蔽。' },
  { id: 'm2', cn: '女祭司', en: 'The High Priestess', img: 'major/2m.jpg',
    up: '直觉敏锐，静待答案浮现，隐藏的真相即将显明。', rev: '忽视直觉、被表象迷惑，或压抑了心事。' },
  { id: 'm3', cn: '女皇', en: 'The Empress', img: 'major/3m.jpg',
    up: '丰盛、滋养与被爱包围，正在孕育美好的成果。', rev: '过度依赖、情感失衡，或忽略了对自己的照顾。' },
  { id: 'm4', cn: '皇帝', en: 'The Emperor', img: 'major/4m.jpg',
    up: '秩序、掌控与责任感，靠规则和实力稳住局面。', rev: '控制欲过强、固执专断，或缺乏决断力。' },
  { id: 'm5', cn: '教皇', en: 'The Hierophant', img: 'major/5m.jpg',
    up: '传统、信念与指引，遵循靠谱的经验与长辈建议。', rev: '墨守成规、被教条束缚，或想挑战权威。' },
  { id: 'm6', cn: '恋人', en: 'The Lovers', img: 'major/6m.jpg',
    up: '心动的联结、双向的吸引，以及重要的抉择。', rev: '犹豫不决、价值观不合，或关系中的失衡。' },
  { id: 'm7', cn: '战车', en: 'The Chariot', img: 'major/7m.jpg',
    up: '意志坚定，势不可挡地朝目标前进，方向由你掌控。', rev: '方向混乱、鲁莽失控，或停滞不前。' },
  { id: 'm8', cn: '力量', en: 'Strength', img: 'major/8m.jpg',
    up: '温柔的坚定，以耐心与勇气驯服内心的猛兽。', rev: '自我怀疑、情绪失控，或用力过猛。' },
  { id: 'm9', cn: '隐士', en: 'The Hermit', img: 'major/9m.jpg',
    up: '独处反思、向内寻找答案，沉淀之后再出发。', rev: '过度封闭、逃避现实，或孤独感过重。' },
  { id: 'm10', cn: '命运之轮', en: 'Wheel of Fortune', img: 'major/10m.jpg',
    up: '转折点到来，运势循环上升，顺势而为。', rev: '时运不济、陷在循环里，需要主动打破。' },
  { id: 'm11', cn: '正义', en: 'Justice', img: 'major/11m.jpg',
    up: '公平公正、因果分明，做出诚实的选择。', rev: '偏颇、逃避责任，或结果不尽公平。' },
  { id: 'm12', cn: '倒吊人', en: 'The Hanged Man', img: 'major/12m.jpg',
    up: '暂停与换位思考，牺牲换来全新的视角。', rev: '无谓的拖延与牺牲，钻牛角尖。' },
  { id: 'm13', cn: '死神', en: 'Death', img: 'major/13m.jpg',
    up: '彻底的结束与蜕变，为新的开始腾出位置。', rev: '抗拒改变、留恋过去，让痛苦被延长。' },
  { id: 'm14', cn: '节制', en: 'Temperance', img: 'major/14m.jpg',
    up: '平衡与调和，耐心地把事物融合得恰到好处。', rev: '失衡、急躁，或过度放纵自己。' },
  { id: 'm15', cn: '恶魔', en: 'The Devil', img: 'major/15m.jpg',
    up: '强烈的欲望与执念，被绑定或沉迷的关系。', rev: '挣脱束缚、看清诱惑，重获自由。' },
  { id: 'm16', cn: '高塔', en: 'The Tower', img: 'major/16m.jpg',
    up: '突如其来的崩塌，打破虚假的安稳，真相浮现。', rev: '慢性崩溃，迟迟不愿放手的隐患。' },
  { id: 'm17', cn: '星星', en: 'The Star', img: 'major/17m.jpg',
    up: '希望与疗愈，温柔的指引，愿望正在实现。', rev: '失去信心、悲观，或希望被暂时遮蔽。' },
  { id: 'm18', cn: '月亮', en: 'The Moon', img: 'major/18m.jpg',
    up: '潜意识浮现，不安与幻象并存，需要辨明真伪。', rev: '迷雾散去、恐惧被看清，真相浮现。' },
  { id: 'm19', cn: '太阳', en: 'The Sun', img: 'major/19m.jpg',
    up: '光明、成功与纯粹的快乐，一切都明朗起来。', rev: '短暂的阴霾、过度乐观，或快乐被延迟。' },
  { id: 'm20', cn: '审判', en: 'Judgement', img: 'major/20m.jpg',
    up: '觉醒与召唤，重新评估过去，获得第二次机会。', rev: '自我批判过度、逃避召唤，犹豫不决。' },
  { id: 'm21', cn: '世界', en: 'The World', img: 'major/21m.jpg',
    up: '圆满达成，一个阶段的完美收束与旅程的完成。', rev: '差最后一步没走完，或迟迟无法收尾。' },

  /* ---------- 圣杯 Cups ---------- */
  { id: 'c1', cn: '圣杯王牌', en: 'Ace of Cups', img: 'cups/1c.jpg',
    up: '新的情感萌芽，爱意与喜悦满溢而出。', rev: '情感被压抑，或付出得不到回应。' },
  { id: 'c2', cn: '圣杯二', en: 'Two of Cups', img: 'cups/2c.jpg',
    up: '双向奔赴的结合，彼此理解与吸引。', rev: '关系失衡、误会，或渐行渐远。' },
  { id: 'c3', cn: '圣杯三', en: 'Three of Cups', img: 'cups/3c.jpg',
    up: '欢聚、友谊与共享的快乐时光。', rev: '社交疲惫、被排挤，或享乐过度。' },
  { id: 'c4', cn: '圣杯四', en: 'Four of Cups', img: 'cups/4c.jpg',
    up: '倦怠与不满足，忽略了眼前的橄榄枝。', rev: '重新振作，愿意接受新的可能。' },
  { id: 'c5', cn: '圣杯五', en: 'Five of Cups', img: 'cups/5c.jpg',
    up: '失落与遗憾，为打翻的杯子伤心。', rev: '走出悲伤，开始看见还剩下的美好。' },
  { id: 'c6', cn: '圣杯六', en: 'Six of Cups', img: 'cups/6c.jpg',
    up: '怀旧与纯真的温情，来自过去的一份馈赠。', rev: '沉浸在回忆里，无法面对当下。' },
  { id: 'c7', cn: '圣杯七', en: 'Seven of Cups', img: 'cups/7c.jpg',
    up: '选择太多、幻想纷飞，需要认清真正想要的。', rev: '迷雾散去，终于做出清晰的选择。' },
  { id: 'c8', cn: '圣杯八', en: 'Eight of Cups', img: 'cups/8c.jpg',
    up: '转身离开，为寻找更深的意义而放弃现状。', rev: '留恋不舍、反复回头，迟迟不离开。' },
  { id: 'c9', cn: '圣杯九', en: 'Nine of Cups', img: 'cups/9c.jpg',
    up: '愿望成真，心满意足的享受时刻。', rev: '表面满足，内心仍觉空虚。' },
  { id: 'c10', cn: '圣杯十', en: 'Ten of Cups', img: 'cups/10c.jpg',
    up: '情感圆满，家庭与关系和谐幸福。', rev: '关系失和，理想与现实存在落差。' },
  { id: 'cp', cn: '圣杯侍从', en: 'Page of Cups', img: 'cups/pc.jpg',
    up: '柔软的心意与浪漫的讯息，感性的新开始。', rev: '情绪化、不切实际，或心意不被珍视。' },
  { id: 'cn', cn: '圣杯骑士', en: 'Knight of Cups', img: 'cups/nc.jpg',
    up: '带着爱意而来的邀约，浪漫而主动。', rev: '空口承诺，情绪反复的追求者。' },
  { id: 'cq', cn: '圣杯王后', en: 'Queen of Cups', img: 'cups/qc.jpg',
    up: '温柔体贴、共情力强，用爱包容一切。', rev: '被情绪淹没，过度付出而失去自己。' },
  { id: 'ck', cn: '圣杯国王', en: 'King of Cups', img: 'cups/kc.jpg',
    up: '情感成熟稳重，能掌控情绪地深爱。', rev: '情感操控、压抑，或表现冷漠。' },

  /* ---------- 星币 Pentacles ---------- */
  { id: 'p1', cn: '星币王牌', en: 'Ace of Pentacles', img: 'pentacles/1p.jpg',
    up: '实实在在的新机会，物质与机会的种子。', rev: '机会流失，投入暂时没有回报。' },
  { id: 'p2', cn: '星币二', en: 'Two of Pentacles', img: 'pentacles/2p.jpg',
    up: '灵活平衡多方事务，随机应变。', rev: '分身乏术、顾此失彼。' },
  { id: 'p3', cn: '星币三', en: 'Three of Pentacles', img: 'pentacles/3p.jpg',
    up: '团队合作与专业被认可，一起把事做好。', rev: '配合不佳，付出被忽视。' },
  { id: 'p4', cn: '星币四', en: 'Four of Pentacles', img: 'pentacles/4p.jpg',
    up: '紧握与储蓄，安全感来自掌控。', rev: '过度吝啬或抓得太紧，该学会放手。' },
  { id: 'p5', cn: '星币五', en: 'Five of Pentacles', img: 'pentacles/5p.jpg',
    up: '匮乏与孤立，需要向外求助。', rev: '渡过难关，温暖的援手出现。' },
  { id: 'p6', cn: '星币六', en: 'Six of Pentacles', img: 'pentacles/6p.jpg',
    up: '给予与接受的平衡，慷慨会有回报。', rev: '不平等的付出，或施舍带着条件。' },
  { id: 'p7', cn: '星币七', en: 'Seven of Pentacles', img: 'pentacles/7p.jpg',
    up: '耐心等待收成，评估长期的投入。', rev: '白费力气，或急于求成。' },
  { id: 'p8', cn: '星币八', en: 'Eight of Pentacles', img: 'pentacles/8p.jpg',
    up: '专注打磨技艺，踏实积累。', rev: '敷衍了事，兴趣缺缺。' },
  { id: 'p9', cn: '星币九', en: 'Nine of Pentacles', img: 'pentacles/9p.jpg',
    up: '自给自足的从容，享受努力得来的成果。', rev: '过度依赖他人，或享受被打破。' },
  { id: 'p10', cn: '星币十', en: 'Ten of Pentacles', img: 'pentacles/10p.jpg',
    up: '长久的富足与传承，稳固的归宿。', rev: '财务纠纷，或缺乏归属感。' },
  { id: 'pp', cn: '星币侍从', en: 'Page of Pentacles', img: 'pentacles/pp.jpg',
    up: '踏实的开始，学习与探索新领域。', rev: '拖延，目标不够清晰。' },
  { id: 'pn', cn: '星币骑士', en: 'Knight of Pentacles', img: 'pentacles/np.jpg',
    up: '稳健可靠地推进，虽然慢但一定到。', rev: '停滞不前，或过于保守。' },
  { id: 'pq', cn: '星币王后', en: 'Queen of Pentacles', img: 'pentacles/qp.jpg',
    up: '务实温暖，把生活和关系都照顾得妥帖。', rev: '忽略自己，为别人耗尽力气。' },
  { id: 'pk', cn: '星币国王', en: 'King of Pentacles', img: 'pentacles/kp.jpg',
    up: '物质与事业上的成功，成熟可靠的支柱。', rev: '固执保守，或只看重利益。' },

  /* ---------- 宝剑 Swords ---------- */
  { id: 's1', cn: '宝剑王牌', en: 'Ace of Swords', img: 'swords/1s.jpg',
    up: '思路清晰、真相大白，突破性的洞察。', rev: '思绪混乱，判断出现偏差。' },
  { id: 's2', cn: '宝剑二', en: 'Two of Swords', img: 'swords/2s.jpg',
    up: '回避抉择，僵持中的脆弱平衡。', rev: '被迫面对，僵局终于被打破。' },
  { id: 's3', cn: '宝剑三', en: 'Three of Swords', img: 'swords/3s.jpg',
    up: '心痛与伤害，难以回避的真相。', rev: '伤口开始愈合，慢慢走出痛苦。' },
  { id: 's4', cn: '宝剑四', en: 'Four of Swords', img: 'swords/4s.jpg',
    up: '休息与休养，暂停下来恢复元气。', rev: '长期疲惫，或过度紧绷无法放松。' },
  { id: 's5', cn: '宝剑五', en: 'Five of Swords', img: 'swords/5s.jpg',
    up: '争执与得失，赢了道理却输了关系。', rev: '和解、放下无谓的竞争。' },
  { id: 's6', cn: '宝剑六', en: 'Six of Swords', img: 'swords/6s.jpg',
    up: '从混乱中转移，向平静过渡。', rev: '不愿离开旧境，问题被拖着走。' },
  { id: 's7', cn: '宝剑七', en: 'Seven of Swords', img: 'swords/7s.jpg',
    up: '隐瞒与策略，需要多留个心眼。', rev: '谎言被揭穿，或选择坦诚相待。' },
  { id: 's8', cn: '宝剑八', en: 'Eight of Swords', img: 'swords/8s.jpg',
    up: '自我设限的困局，恐惧捆住了手脚。', rev: '挣脱束缚，看见新的出路。' },
  { id: 's9', cn: '宝剑九', en: 'Nine of Swords', img: 'swords/9s.jpg',
    up: '焦虑与失眠，被想象出的恐惧折磨。', rev: '噩梦过去，愿意倾诉与求助。' },
  { id: 's10', cn: '宝剑十', en: 'Ten of Swords', img: 'swords/10s.jpg',
    up: '彻底的结束与背叛，触底之后就是转机。', rev: '缓慢复原，最坏的时刻已经过去。' },
  { id: 'sp', cn: '宝剑侍从', en: 'Page of Swords', img: 'swords/ps.jpg',
    up: '好奇敏锐，带来新的消息与想法。', rev: '多疑八卦，或说话不够谨慎。' },
  { id: 'sn', cn: '宝剑骑士', en: 'Knight of Swords', img: 'swords/ns.jpg',
    up: '雷厉风行、直来直往的冲劲。', rev: '鲁莽冲动，说话容易伤人。' },
  { id: 'sq', cn: '宝剑王后', en: 'Queen of Swords', img: 'swords/qs.jpg',
    up: '理性清醒，洞察力强，界限分明。', rev: '刻薄冷淡，或过度防备。' },
  { id: 'sk', cn: '宝剑国王', en: 'King of Swords', img: 'swords/ks.jpg',
    up: '冷静的权威，用理性与原则做判断。', rev: '独断专横，或滥用理性。' },

  /* ---------- 权杖 Wands ---------- */
  { id: 'w1', cn: '权杖王牌', en: 'Ace of Wands', img: 'wands/1w.jpg',
    up: '灵感与热情的火花，行动的最佳时机。', rev: '热情消退，计划难以启动。' },
  { id: 'w2', cn: '权杖二', en: 'Two of Wands', img: 'wands/2w.jpg',
    up: '展望未来，站在起点做长远规划。', rev: '犹豫不前，或格局太小。' },
  { id: 'w3', cn: '权杖三', en: 'Three of Wands', img: 'wands/3w.jpg',
    up: '视野打开，等待远方的回报。', rev: '计划受阻，进展慢于预期。' },
  { id: 'w4', cn: '权杖四', en: 'Four of Wands', img: 'wands/4w.jpg',
    up: '值得庆祝的安稳与喜悦，阶段性的安定。', rev: '庆祝被推迟，关系里有些小摩擦。' },
  { id: 'w5', cn: '权杖五', en: 'Five of Wands', img: 'wands/5w.jpg',
    up: '竞争与摩擦，多方角力中彼此磨合。', rev: '化解冲突，停止内耗。' },
  { id: 'w6', cn: '权杖六', en: 'Six of Wands', img: 'wands/6w.jpg',
    up: '胜利与被认可，赢得掌声。', rev: '被低估，信心受挫。' },
  { id: 'w7', cn: '权杖七', en: 'Seven of Wands', img: 'wands/7w.jpg',
    up: '坚守立场，勇敢捍卫自己的位置。', rev: '力不从心，或疲于应付。' },
  { id: 'w8', cn: '权杖八', en: 'Eight of Wands', img: 'wands/8w.jpg',
    up: '进展飞快，消息与行动都来得迅速。', rev: '延迟、停滞，或节奏混乱。' },
  { id: 'w9', cn: '权杖九', en: 'Nine of Wands', img: 'wands/9w.jpg',
    up: '带伤坚持，最后一关咬牙撑住。', rev: '疲惫到极限，或过度警惕。' },
  { id: 'w10', cn: '权杖十', en: 'Ten of Wands', img: 'wands/10w.jpg',
    up: '承担过重，责任压得喘不过气。', rev: '学会卸下，把担子分出去。' },
  { id: 'wp', cn: '权杖侍从', en: 'Page of Wands', img: 'wands/pw.jpg',
    up: '充满热情的新尝试，大胆去探索。', rev: '三分钟热度，方向不定。' },
  { id: 'wn', cn: '权杖骑士', en: 'Knight of Wands', img: 'wands/nw.jpg',
    up: '热烈追求，行动派的浪漫。', rev: '冲动急躁，来得快去得也快。' },
  { id: 'wq', cn: '权杖王后', en: 'Queen of Wands', img: 'wands/qw.jpg',
    up: '自信迷人，有感染力的热度。', rev: '情绪化、嫉妒，或缺乏安全感。' },
  { id: 'wk', cn: '权杖国王', en: 'King of Wands', img: 'wands/kw.jpg',
    up: '有远见的领导者，把热情变成事业。', rev: '独断暴躁，听不进别人意见。' }
];
